services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        API_URL: http://ec2-3-15-20-92.us-east-2.compute.amazonaws.com/
    ports:
      - "80:80"

  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./qwen2.5-coder-7b.gguf:/app/qwen2.5-coder-7b.gguf
